//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_Table
    {
        public string ImgName { get; set; }
        public byte[] ImgObject { get; set; }
        public string ImgDescription { get; set; }
        public int ImgID { get; set; }
        public string Extension { get; set; }
    }
}
